### ISSUE TITLE
Big endian not supported

### ISSUE THREAD

**Issue by user115122** [256dpi/lwmqtt#1]
Tried the example and the tests cases on x86, mips little endian and powerpc big endian.
Success on all but big endian.

Running the example results in the connection being closed after the first client to server message (connect) sent, socket gets connection reset by peer (error 104).

Turns out there's code in packet.c that's endian dependent, specifically using unions to get bits from bytes, according to https://stackoverflow.com/a/3497474 (ISO C99, 6.7.2.1p10). 

There are many ways to solve this. I'm attaching a patch that tries to focus more on readability and less on performance.

[patch.txt](https://github.com/256dpi/lwmqtt/files/1398789/patch.txt)

**Comment by 256dpi** [comment]
Thanks! Based on your patch I came up with the following modifications:
https://github.com/256dpi/lwmqtt/pull/2

Can you test the branch and confirm that works on your machine?

**Comment by 256dpi** [comment]
I accidentally pushed some other cleanups to that branch. Sorry for the mess.

**Comment by user115122** [comment]
I verified the branch big-endian on my powerpc target, it works fine. Thanks!
