### ISSUE TITLE
empty usernames are not encoded correctly

### ISSUE THREAD

**Issue by dustin** [256dpi/lwmqtt#10]
In generating connect requests, I found that intentionally specifying an empty string as a username is interpreted as no username, so the field is omitted altogether.

AFAICT, an empty username is valid, but is required if you want to specify a password without a username.

I'm not sure how much this actually matters, but it's a test failure I'm working around currently.

**Comment by dustin** [comment]
There's a similar issue with passwords.  For the purposes of my tests, I've just converted `""` to `Nothing` in both cases to get all the tests passing.

**Comment by 256dpi** [comment]
Fixed in ebf53c0. Will be available in next release.
