### ISSUE TITLE
Unable to find memory.h on build

### ISSUE THREAD

**Issue by napei** [256dpi/lwmqtt#13]
I'm getting an error when trying to build this demo project from GCP. https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/tree/master/examples/Esp32-lwmqtt

`.pio\libdeps\nodemcu-32s\LWMQTT\src\os\unix.c:3:20: fatal error: memory.h: No such file or directory`

Not sure why I can't get to `memory.h`. I'm using PlatformIO (latest versions) on windows, with the Arduino APIs (C++) on an ESP32.

**Comment by 256dpi** [comment]
Closing as stale, please reopen if issue persists.
